### ISSUE TITLE
How to increase upload limit of 2MB?

### ISSUE THREAD

**Issue by metamorphious** [stephenliang/mediawiki-dockerfile#3]
Is there a possibility to increase the upload size limit? I think the php.ini has to be adjusted.
Perhaps the ini file could be linked in the container from a volume?

**Comment by stephenliang** [comment]
Either create your own php.ini or you can volume mount it. Either way, it would be done from your image rather than this template image.

**Comment by cdauth** [comment]
Create a file `uploads.ini` like this:

```
upload_max_filesize = 2000M
post_max_size = 2000M
max_execution_time = 7200
max_file_uploads = 1000
```

And mount it as a volume like this: `./uploads.ini:/etc/php5/fpm/conf.d/uploads.ini:ro`.
